# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41f263a6d7f556e486e79887731c4f5a"
name = "feedpilot-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
