type HistoryItem = {
  id: string;
  source: string;
  status: string;
  impactDelta: number | null;
  seoScoreBefore: number | null;
  seoScoreAfter: number | null;
  productTitleBefore: string;
  productTitleAfter: string;
  createdAt: string;
};

type WeeklyInsight = {
  windowDays: number;
  totalOptimizations: number;
  appliedCount: number;
  failedCount: number;
  automatedCount: number;
  manualCount: number;
  improvedProducts: number;
  totalImpactDelta: number;
  avgImpactDelta: number;
  avgSeoBefore: number;
  avgSeoAfter: number;
  summaryText: string;
  topProducts: Array<{
    id: string;
    productId: string;
    titleBefore: string;
    titleAfter: string;
    impactDelta: number;
    seoScoreBefore: number | null;
    seoScoreAfter: number | null;
    createdAt: string;
  }>;
};

export function OptimizationHistoryPanel(props: {
  weeklyInsight: WeeklyInsight;
  optimizationHistory: HistoryItem[];
}) {
  const { weeklyInsight, optimizationHistory } = props;

  return (
    <div style={{ marginTop: 24 }}>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1.2fr 1fr",
          gap: 16,
          alignItems: "start",
        }}
      >
        <div
          style={{
            background: "#fff",
            border: "1px solid #e5e7eb",
            borderRadius: 16,
            padding: 20,
          }}
        >
          <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 8 }}>
            Weekly Insight
          </div>
          <div style={{ color: "#6b7280", fontSize: 14, marginBottom: 16 }}>
            Continuous optimization results generated by FeedPilot.
          </div>

          <div
            style={{
              background: "#f9fafb",
              borderRadius: 12,
              padding: 14,
              fontSize: 14,
              lineHeight: 1.7,
              marginBottom: 16,
            }}
          >
            FeedPilot applied {weeklyInsight.appliedCount} optimizations in the last{" "}
            {weeklyInsight.windowDays} days.{" "}
            {weeklyInsight.appliedCount > 0
              ? `${weeklyInsight.improvedProducts} products improved with measurable SEO gains, generating a total impact of ${
                  weeklyInsight.totalImpactDelta >= 0 ? "+" : ""
                }${weeklyInsight.totalImpactDelta}.`
              : "System is monitoring your catalog for new opportunities."}{" "}
            Continuous improvements are building your catalog performance over time.
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
              gap: 12,
            }}
          >
            <MetricCard label="Applied" value={weeklyInsight.appliedCount} />
            <MetricCard label="Improved" value={weeklyInsight.improvedProducts} />
            <MetricCard label="Impact Δ" value={weeklyInsight.totalImpactDelta} />
            <MetricCard label="Automation" value={weeklyInsight.automatedCount} />
          </div>

          <div style={{ marginTop: 18 }}>
            <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 10 }}>
              Top improved products
            </div>

            {weeklyInsight.topProducts.length === 0 ? (
              <div style={{ color: "#6b7280", fontSize: 14 }}>
                No applied optimizations in the last 7 days.
              </div>
            ) : (
              weeklyInsight.topProducts.map((item) => (
                <div
                  key={item.id}
                  style={{
                    border: "1px solid #e5e7eb",
                    borderRadius: 12,
                    padding: 12,
                    marginBottom: 10,
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      gap: 12,
                      alignItems: "center",
                    }}
                  >
                    <div style={{ fontWeight: 700 }}>{item.titleAfter}</div>
                    <div
                      style={{
                        background: "#ecfdf3",
                        color: "#027a48",
                        border: "1px solid #abefc6",
                        borderRadius: 999,
                        padding: "4px 10px",
                        fontSize: 12,
                        fontWeight: 700,
                      }}
                    >
                      +{item.impactDelta}
                    </div>
                  </div>

                  <div style={{ marginTop: 6, color: "#6b7280", fontSize: 13 }}>
                    Score: {display(item.seoScoreBefore)} → {display(item.seoScoreAfter)}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        <div
          style={{
            background: "#fff",
            border: "1px solid #e5e7eb",
            borderRadius: 16,
            padding: 20,
          }}
        >
          <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 8 }}>
            Optimization History
          </div>
          <div style={{ color: "#6b7280", fontSize: 14, marginBottom: 16 }}>
            Every applied change becomes proof for retention and billing.
          </div>

          {optimizationHistory.length === 0 ? (
            <div style={{ color: "#6b7280", fontSize: 14 }}>
              No history yet. The next applied optimization will start building your value record.
            </div>
          ) : (
            optimizationHistory.map((item) => (
              <div
                key={item.id}
                style={{
                  border: "1px solid #e5e7eb",
                  borderRadius: 12,
                  padding: 12,
                  marginBottom: 10,
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    gap: 12,
                    marginBottom: 6,
                  }}
                >
                  <div style={{ fontWeight: 700, fontSize: 14 }}>
                    {item.productTitleAfter}
                  </div>
                  <div style={{ fontSize: 12, color: "#6b7280" }}>
                    {formatDate(item.createdAt)}
                  </div>
                </div>

                <div style={{ fontSize: 13, color: "#6b7280", marginBottom: 6 }}>
                  {item.source} · {item.status}
                </div>

                <div style={{ fontSize: 13, color: "#111827" }}>
                  {formatHistoryScoreLine(item)}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

function MetricCard(props: { label: string; value: number }) {
  return (
    <div
      style={{
        border: "1px solid #e5e7eb",
        borderRadius: 12,
        padding: 12,
        background: "#fff",
      }}
    >
      <div style={{ color: "#6b7280", fontSize: 12, marginBottom: 6 }}>
        {props.label}
      </div>
      <div style={{ fontSize: 24, fontWeight: 800 }}>{props.value}</div>
    </div>
  );
}

function formatHistoryScoreLine(item: HistoryItem) {
  const before = isFiniteNumber(item.seoScoreBefore) ? item.seoScoreBefore : null;
  const after = isFiniteNumber(item.seoScoreAfter) ? item.seoScoreAfter : null;
  const storedDelta = isFiniteNumber(item.impactDelta) ? item.impactDelta : null;

  if (before === null) {
    return after === null
      ? "Legacy record · score unavailable"
      : `Score after: ${after} · Legacy record (before score unavailable)`;
  }

  if (after === null) {
    return `Score before: ${before} · after score unavailable`;
  }

  const delta = storedDelta ?? after - before;
  const deltaSign = delta > 0 ? "+" : "";
  return `${before} → ${after} · Δ ${deltaSign}${delta}`;
}

function display(value: number | null | undefined) {
  return isFiniteNumber(value) ? value : "-";
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function formatDate(value: string) {
  const date = new Date(value);
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}
